server:
  port: 9999

spring:
  application:
    name: yzc-es
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
es:
  host: localhost:9200
  username:
  password:


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
      #租约续订间隔时间（默认30秒），如下所示每间隔 5s 向服务端发送一次心跳，证明自己依然"存活"
      lease-renewal-interval-in-seconds: 3 # 5秒一次心跳
      #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
      # 租约到期时间（默认90秒），如下所示，告诉服务端如果我 6s 之内没有给你发心跳，就代表我"死"了，将我踢出掉
      lease-expiration-duration-in-seconds: 6

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "threaddump,heapdump,health,info,service-registry,shutdown"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
ribbon:
  ReadTimeout: 2000000
  ConnectTimeout: 2000000
  eureka:
    enabled: true
  # 同一实例最大重试次数，不包括首次调用
  MaxAutoRetries: 1
  # 重试其他实例的最大重试次数，不包括首次所选的server
  MaxAutoRetriesNextServer: 2
  # 是否所有操作都进行重试
  #OkToRetryOnAllOperations: true

# Hystrix线程池核心线程数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      # 设置进入熔断器的阈值个数
      circuitBreaker:
        requestVolumeThreshold: 1000
      # 最大回退个数
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 50
  threadpool:
    default:
      coreSize: 500
logging:
  config: classpath:log4j2.yml